- name: create
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml



- name : create a jenkins job using authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/job.xml') }}"
    name: test
    url: http://172.31.13.229:8080
    user: admin
    password: admin123
  loop:
    - frontend
    - catalogue