- name: create
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml



- name : create a jenkins job using authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item}}"
    url: http://172.31.3.158:8080
    user: admin
    password: admin123
  loop:
    - frontend
    - catalogue
    - cart