- name : create a jenkins job using authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.3.158:8080
    user: admin
    password: admin123
  loop:
    - CIPipelines

- name: create include tasks
  ansible.builtin.include_tasks: pipeline.yml
  loop:
    - {name: "frontend",dir: "CIPipelines"}
    - {name: "cart",dir: "CIPipelines"}
    - {name: "catalogue",dir: "CIPipelines"}
    - {name: "payment",dir: "CIPipelines"}
    - {name: "shipping",dir: "CIPipelines"}
    - {name: "user",dir: "CIPipelines"}