- name: create
  ansible.builtin.template:
    src: jobs.xml
    dest: /tmp/jobs.xml




- name : create a jenkins job using authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/jobs.xml') }}"
    name: "{{item}}"
    url: http://172.31.3.158:8080
    user: admin
    password: admin123
