

- name: create config
  ansible.builtin.template:
    src: jobs.xml
    dest: /tmp/jobs.xml


- name : create a jenkins job using authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/jobs.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.13.229:8080
    user: admin
    password: admin123
